Sign up form, use commit.files to determine file heritage in diffs, repo/create

diff --git a/bin/process_tree b/bin/process_tree
--- a/bin/process_tree
+++ b/bin/process_tree
@@ -3,6 +3,18 @@
 repo=$1
 path=$2
 
+if [[ -z "$path" ]]
+then
+    if [[ "$repo" =~ ([^/]+/+[^/]+)/*$ ]]
+    then
+        path=${BASH_REMATCH[1]}
+        echo "Using path ${path}"
+    else
+        echo "Could not extract path from ${repo}"
+        exit 1
+    fi
+fi
+
 echo 'Pull repo'
 if [[ -d repos/$path/repo ]]
 then
